# Generated by Django 3.2.4 on 2021-06-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gethouse', '0002_alter_profile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
